# AI ja koneoppiminen - tehtävä 1

Palauttakaa tämän ipynb-tiedosto pohjana

## 1.1 Markdown
Kirjoita seuraavat asiat markdown-kenttään:
 1. Väliotsikko: "Markdown-lista"
 2. Numeroitu lista
 3. Väliotsikko: "Markdown-kuva"
 4. Upota kuva markdownilla. Kuvan linkki: https://www.frostbit.fi/wp-content/uploads/2024/08/Gamejam2024-header-webpage.jpg
 5. Väliotsikko: "Markdown-linkki"
 6. Markdown-linkki osoitteeseen: https://www.lapinamk.fi/fi

## Markdown-lista
1. testi1
2. testi2
3. testi3

## Markdown-kuva
![KUVA](https://www.frostbit.fi/wp-content/uploads/2024/08/Gamejam2024-header-webpage.jpg)

## Markdown-linkki
[AMK-SIVU](https://www.lapinamk.fi/fi)

## 1.2 Numpy

Tee seuraavat numpy-harjoitukset:

In [1]:
# Tuo Numpy -kirjasto tässä
import numpy as np

In [3]:
# Tässä luodaan satunnaisten lukujen yksiulotteinen numpy ndarray
numpy_array = np.random.random(20)
numpy_array

array([0.86440051, 0.06892858, 0.98526928, 0.18768639, 0.95202186,
       0.71739929, 0.7406352 , 0.5841368 , 0.11659278, 0.23693378,
       0.01025401, 0.4993498 , 0.46218685, 0.97547161, 0.62885956,
       0.37078434, 0.31076232, 0.07687386, 0.66433079, 0.58548064])

In [4]:
# Laske numpy_array lukujen keskiarvo tähän:
numpy_array_mean = numpy_array.mean()
numpy_array_mean

np.float64(0.5019179123612575)

In [5]:
# Tässä luodaan satunnaisten lukujen kolmiulotteinen numpy ndarray
numpy_matrix = np.random.random(size=(20, 3))
numpy_matrix

array([[0.35534273, 0.56204377, 0.88348242],
       [0.16651496, 0.04827282, 0.68888262],
       [0.23794159, 0.29932577, 0.50155693],
       [0.31009186, 0.08503848, 0.96670932],
       [0.38359913, 0.98425375, 0.04027949],
       [0.13178013, 0.19356328, 0.6507773 ],
       [0.56441691, 0.65872717, 0.08910529],
       [0.89296297, 0.05625773, 0.89052993],
       [0.01906596, 0.01858333, 0.91059471],
       [0.90103424, 0.54273364, 0.86879026],
       [0.72385291, 0.05045685, 0.08900392],
       [0.89410422, 0.85605004, 0.79308848],
       [0.60829358, 0.26616526, 0.02128316],
       [0.83988706, 0.35054829, 0.71236336],
       [0.29690228, 0.3256476 , 0.47042426],
       [0.73532637, 0.886925  , 0.13512294],
       [0.47971161, 0.40104065, 0.20235553],
       [0.1354707 , 0.68476653, 0.60374391],
       [0.73547662, 0.03088941, 0.55898486],
       [0.08593944, 0.56788928, 0.81042885]])

In [6]:
# Laske numpy_matrix keskiarvot per sarake:
numpy_matrix_mean_per_column = numpy_matrix.mean(axis=0)
numpy_matrix_mean_per_column

array([0.47488576, 0.39345893, 0.54437538])

## 1.3 Pandas

Tee seuraavan Pandas-harjoitukset

In [7]:
# Tuo Pandas -kirjasto tässä
import pandas as pd

In [9]:
# Luodaan DataFrame, joka sisältää tietoa opiskelijoista
data = {
    'Nimi': ['Anna', 'Matti', 'Liisa', 'Pekka'],
    'Ikä': [22, 21, 23, 24],
    'Arvosana': [5, 4, 3, 5]
}
df = pd.DataFrame(data)

In [10]:
# Laske opiskelijoiden keski-ikä:
mid_age = df['Ikä'].mean()
mid_age

np.float64(22.5)

In [11]:
# Suodata ne opiskelijat, joiden arvosana on yli 3
filtered_students = df[df['Arvosana'] > 3]
filtered_students

Nimi  Ikä  Arvosana
0   Anna   22         5
1  Matti   21         4
3  Pekka   24         5